CREATE TABLE [report].[DatabaseObjectColumn] (
    [ReportSQLObjectColumnId]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [ServerName]                    VARCHAR (100)  NOT NULL,
    [DatabaseName]                  NVARCHAR (128) NOT NULL,
    [TableSchemaName]               NVARCHAR (128) NOT NULL,
    [TableName]                     NVARCHAR (128) NOT NULL,
    [ColumnName]                    [sysname]      NOT NULL,
    [column_id]                     INT            NOT NULL,
    [TypeCode]                      VARCHAR (10)   NULL,
    [TypeDescriptionUser]           NVARCHAR (50)  NULL,
    [DocumentationDescription]      NVARCHAR (MAX) NULL,
    [datatype]                      NVARCHAR (100) NULL,
	[DataTypeExtension]			    NVARCHAR (100) NULL,
    [length]                        VARCHAR (10)   NULL,
    [collation_name]                [sysname]      NULL,
    [is_nullable]                   BIT            NOT NULL,
    [is_identity]                   BIT            NOT NULL,
    [is_computed]                   BIT            NOT NULL,
    [is_primary_key]                BIT            NOT NULL,
	[Column_Default]                NVARCHAR (MAX) NULL,
    [PKType]                        VARCHAR (25)   NULL,
    [FK_NAME]                       NVARCHAR (128) NULL,
    [ReferencedSchemaName]          NVARCHAR (128) NULL,
    [ReferencedObjectName]          NVARCHAR (128) NULL,
    [ReferencedTypeCode]            VARCHAR (10)   NULL,
    [ReferencedColumn]              NVARCHAR (128) NULL,
    [ReferencedTypeDescriptionUser] NVARCHAR (50)  NULL,
    [FKGeneratedName]               NVARCHAR (MAX) NULL,
    [DocumentationLoadDate]         DATETIME2 (7)  NOT NULL,
    [BusinessKey]                   VARCHAR (250)  NULL,
    CONSTRAINT [PK_SqlObjectColumn] PRIMARY KEY CLUSTERED ([ReportSQLObjectColumnId] ASC)
);

