CREATE TABLE [dbo].[MDSCHEMA_MEASUREGROUPS] (
    [CATALOG_NAME]         VARCHAR (255) NULL,
    [SCHEMA_NAME]          VARCHAR (255) NULL,
    [CUBE_NAME]            VARCHAR (255) NULL,
    [MEASUREGROUP_NAME]    VARCHAR (255) NULL,
    [DESCRIPTION]          VARCHAR (255) NULL,
    [IS_WRITE_ENABLED]     BIT           NULL,
    [MEASUREGROUP_CAPTION] VARCHAR (255) NULL
);

