CREATE TABLE [dbo].[MDSCHEMA_MEASUREGROUP_DIMENSIONS] (
    [CATALOG_NAME]                VARCHAR (255) NULL,
    [SCHEMA_NAME]                 VARCHAR (255) NULL,
    [CUBE_NAME]                   VARCHAR (255) NULL,
    [MEASUREGROUP_NAME]           VARCHAR (255) NULL,
    [MEASUREGROUP_CARDINALITY]    VARCHAR (255) NULL,
    [DIMENSION_UNIQUE_NAME]       VARCHAR (255) NULL,
    [DIMENSION_CARDINALITY]       VARCHAR (255) NULL,
    [DIMENSION_IS_VISIBLE]        BIT           NULL,
    [DIMENSION_IS_FACT_DIMENSION] BIT           NULL,
    [DIMENSION_PATH]              VARCHAR (255) NULL,
    [DIMENSION_GRANULARITY]       VARCHAR (255) NULL
);

