CREATE TYPE [dbo].[ColumnDocTableType] AS TABLE (
    [ServerName]                NVARCHAR (128) NULL,
    [DatabaseName]              NVARCHAR (128) NULL,
    [ObjectType]                VARCHAR (10)   NULL,
    [SchemaName]                NVARCHAR (128) NULL,
    [ObjectName]                NVARCHAR (128) NULL,
    [ColumnName]                [sysname]      NULL,
    [column_id]                 INT            NULL,
    [datatype]                  [sysname]      NULL,
    [max_length]                SMALLINT       NULL,
    [precision]                 TINYINT        NULL,
    [scale]                     TINYINT        NULL,
    [collation_name]            [sysname]      NULL,
    [is_nullable]               BIT            NULL,
    [is_identity]               BIT            NULL,
    [is_computed]               BIT            NULL,
    [is_primary_key]            BIT            NULL,
    [ident_col_seed_value]      INT            NULL,
    [ident_col_increment_value] INT            NULL,
    [Column_Default]            NVARCHAR (MAX) NULL,
    [DocumentationDescription]  NVARCHAR (MAX) NULL);

